id: P466F2DB5
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA00KG07618
  instance_id: http://purl.bdrc.io/resource/IE00KG07618
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - རྫོགས་པ་ཆེན་པོའི་རྣམ་གཞག་མཐོང་གྲོལ་བྱིན་རླབས་འབར་བ།
  alt_title:
    zh-latn-pinyin-x-ndia:
    - zheng fa da yuan man xian jian jie tuo wei li guang ming lun
  author: http://purl.bdrc.io/resource/P7431
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    93aa08a16e02427398b0dc98407aa3a7:
      title: པོད ༡་རྫོགས་པ་ཆེན་པོའི་རྣམ་གཞག་མཐོང་གྲོལ་བྱིན་རླབས་འབར་བ
      volume_number: 1
      base_file: UT00KG07618_I00KG08421_0000.txt
      reference: http://purl.bdrc.io/resource/VL4C42CAE030CEF16C
      image_group: I00KG08421
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW00KG07618
  - http://purl.bdrc.io/resource/W00KG07618
  ocr_software: Namsel
created_at: '2021-12-22T10:17:22.271258'
last_modified_at: '2021-12-22T10:17:22.271266'
statistics:
  total_words: 194000
  total_non_words: 23258
quality:
  non_words_ratio: 0.12
